import os , shutil
import sys

__pythonexePath = "{}/venv/Scripts/python".format(sys.path[1])
# os.system("{} -m pip install pip==22.2.2".format(__pythonexePath))
# os.system("{} -m pip install setuptools==63.2.0".format(__pythonexePath))
# os.system("{} -m pip install python-dotenv==0.21.0".format(__pythonexePath))
# os.system("{} -m pip install gitpython==3.1.27".format(__pythonexePath))
# os.system("{} -m pip install paramiko==2.11.0".format(__pythonexePath))
# os.system("{} -m pip install datetime==4.5".format(__pythonexePath))
# os.system("{} -m pip install pandas==1.4.4".format(__pythonexePath))
# os.system("{} -m pip install numpy==1.22.4".format(__pythonexePath))
# os.system("{} -m pip install psycopg2==2.9.3".format(__pythonexePath))
# os.system("{} -m pip install pyodbc==4.0.34".format(__pythonexePath))
# os.system("{} -m pip install SQLAlchemy==1.4.41".format(__pythonexePath))
# os.system("{} -m pip install pycaret==3.0.0rc2".format(__pythonexePath))
# os.system("{} -m pip install xgboost==1.6.2".format(__pythonexePath))
# os.system("{} -m pip install catboost==1.0.6".format(__pythonexePath))
# os.system("{} -m pip install scikit-learn==1.1.2".format(__pythonexePath))
# os.system("{} -m pip install gensim==4.2.0".format(__pythonexePath))
# os.system("{} -m pip install tqdm==4.64.1".format(__pythonexePath))
# os.system("{} -m pip install openpyxl==3.0.10".format(__pythonexePath))
# os.system("{} -m pip install matplotlib==3.6.0".format(__pythonexePath))
# os.system("{} -m pip install explainerdashboard==0.4.0".format(__pythonexePath))
os.system("{} -m pip install networkx==2.8.8".format(__pythonexePath))

